export const STORY_CHAPTERS = [
// Rozdział 1
`Rozdział 1: Świat po wojnie
Słońce powoli wyłaniało się zza chmury pyłu, rozświetlając krajobraz w odcieniach rdzawej czerwieni i brudnej żółci. Ziemia była spękana, a na horyzoncie widać było ruiny dawnych miast – betonowe szkielety niszczone przez czas. Porzucone wraki samochodów tworzyły labirynty, w których czasem błyszczały oczy dzikich zwierząt. Świat po wojnie nuklearnej, wywołanej konfliktem Rosji z Ukrainą, nie przypominał niczego, co znano wcześniej. Klimat uległ destrukcji, wirusy mutowały, a ludzkość znalazła się na krawędzi wyginięcia. Ci, którzy przetrwali, zbudowali „fortece“– oazy technologii i porządku. Dostarczanie towarów między fortecami było jednym z najniebezpieczniejszych zajęć, pełnym zagrożeń ze strony bandytów, mutantów i radioaktywnych pustkowi. Tylko najtwardsi przetrwali, jak John, znany jako NightRider.
Jego ciężarówka, Dominator, była legendą – potężną, opancerzoną maszyną gotową na każde wyzwanie.`,

// Rozdział 2
`Rozdział 2: John i Dominator
W oddali dało się usłyszeć niski pomruk silnika. Dominator, niczym żywy organizm, wydawał się być częścią tego surowego krajobrazu. W jego kabinie John, z twarzą pełną determinacji, wpatrywał się w pustkowie. Nie był bohaterem. Był ocalałym. Dominator nie był zwykłą maszyną. Był partnerem, obrońcą i bronią. Jego masywna, opancerzona sylwetka jarzyła się w porannym świetle, gdy NightRider włączał systemy. Z głośników rozległ się syntetyczny głos: – Wszystkie systemy sprawne. Gotowy do drogi, John. - Dzięki, przyjacielu – odpowiedział John, siadając w fotelu kierowcy. – Miejmy nadzieję, że dziś obejdzie się bez większych komplikacji. Dominator był wyposażony w wojskową sztuczną inteligencję, wcześniej używaną w dronach bojowych. Teraz jego misją było jedno: ochrona Johna i dostarczenie ładunku. Jednak Dominator potrafił więcej. Rozumiał sarkazm, znał dowcipy Johna i analizował sytuacje z niemal ludzką intuicją. John westchnął ciężko, patrząc na krajobraz za przednią szybą. Wspomnienia wojny wracały do niego falami – oślepiające wybuchy, krzyki, dym przesłaniający niebo. Był żołnierzem, jednym z najlepszych. Walczył na pierwszej linii, nie wiedząc, że wojna, którą prowadził, pochłonie nie tylko jego wrogów, ale i wszystko, co kochał. Rodzina Johna – jego żona i córka – zginęły podczas pierwszych ataków nuklearnych. Tego dnia stracił sens życia, ale nie pozwolił, by pochłonęła go rozpacz. Zamiast tego wstał z kolan i odnalazł nowe przeznaczenie. Teraz jego misją było dostarczanie ładunków, które mogły ratować inne rodziny. To była jego pokuta, jego sposób na odnalezienie sensu w świecie, który wydawał się stracony. Przejeżdżając przez pustkowia, czuł, że Dominator stał się nie tylko maszyną, ale także symbolem jego własnego odrodzenia. Choć wojna odebrała mu wszystko, to właśnie w tych pustkowiach odkrył nową misję – być łącznikiem między ostatnimi bastionami ludzkości. - Gotowy, przyjacielu? – zapytał, spoglądając na pulsujące światła na desce rozdzielczej. - Zawsze, John – odpowiedziała maszyna. Tym razem podróż miała być inna. John czuł, że coś zmieni się na zawsze, choć nie wiedział jeszcze co.`,

// Rozdział 3
`Rozdział 3: Spotkanie w fortecy
Brama fortecy zaskrzypiała, gdy mechaniczne ramiona zaczęły ją otwierać. Dominator wjechał na główny plac, rzucając cień na grupę mieszkańców. Powietrze było gęste od napięcia – każde wejście kogoś z zewnątrz wywoływało zarówno nadzieję, jak i obawy. W tym świecie każdy przybysz mógł być równie dobrze zbawcą, jak i zagrożeniem. John zeskoczył z kabiny, jego ciężkie buty wzbiły kurz. Wokół zebrała się mała grupa ludzi, przyglądając się z zaciekawieniem, ale i niepokojem. Nagle tłum rozstąpił się, a zza niego wyszła kobieta. Jej oczy były pełne determinacji, choć na twarzy malował się cień zmęczenia. - NightRider? – Jej głos brzmiał stanowczo, ale dało się w nim wyczuć ulgę. John spojrzał na nią uważnie. Kobieta miała na ramieniu stary karabin, a jej sylwetka zdradzała, że nie była przyzwyczajona do wygód. Towarzyszył jej chłopiec, kurczowo trzymający się jej dłoni. - Kim jesteś? – zapytał John, zdejmując okulary przeciwsłoneczne i chowając je do kieszeni swojej kurtki. - Emma, przyjaciele mówią mi Em, a raczej mówili...– przedstawiła się. - A to mój syn, Leo. Potrzebujemy twojej pomocy. John zmarszczył brwi. – Pomocy? Nie jestem ratownikiem, tylko dostawcą. Emma zrobiła krok w jego stronę, patrząc mu prosto w oczy. – Ta forteca jest skazana na zagładę. Brakuje nam jedzenia, wody, a ostatnie ataki mutantów... – Jej głos zadrżał. – Jeśli tu zostaniemy, to kwestia czasu, aż wszyscy zginą. - To nie mój problem – powiedział John oschle, odwracając się w stronę Dominatora. Ale zanim zdążył wejść do kabiny, usłyszał głos chłopca: - Proszę, panie NightRider. Moja mama mówi, że jest pan bohaterem. John zatrzymał się w pół kroku, czując dziwny ucisk w piersi. Spojrzał na Leo, którego wielkie, błyszczące oczy przypominały mu kogoś, kogo stracił dawno temu. - Dlaczego ja? – zapytał, spoglądając na Emmę. - Bo słyszałam historie o tobie i Dominatorze. Słyszałam, że nigdy nie odmawiasz, gdy ktoś naprawdę potrzebuje pomocy. John westchnął ciężko, pocierając dłonią kark. – Nie obchodzi mnie, co słyszałaś. Ale..., jeśli was zabiorę, to tylko dlatego, że jestem już tutaj. I nie liczcie na luksusy. Emma uśmiechnęła się lekko, jakby właśnie zyskała nową nadzieję. – Dziękuję. Leo wyciągnął rękę w stronę Johna. – Czy mogę usiąść w Dominatorze? John zmrużył oczy, ale kącik jego ust uniósł się lekko. – Jeśli się nie boisz, to może cię wpuszczę. Ale nie dotykaj niczego, czego nie rozumiesz. - Obiecuję! – zawołał Leo z entuzjazmem, którego brakowało w tym świecie.
Dominator i jego rola. Gdy John przygotowywał Dominatora do drogi, maszyna „obudziła się”. - Nowi pasażerowie, John? – zapytał Dominator, a jego głos wybrzmiał w kabinie. - Wygląda na to, że tak. Masz z tym jakiś problem? - Moje systemy są zaprojektowane do ochrony towarów i ciebie, nie do opieki nad dziećmi. John uśmiechnął się pod nosem. – Może pora na aktualizację, kolego? Leo, który siedział w kabinie, spojrzał na deskę rozdzielczą z szeroko otwartymi oczami. – On mówi?! - I słucha – odpowiedział Dominator. – Więc radzę ci uważać na to, co mówisz, młody człowieku! Leo zaśmiał się, a jego śmiech rozbrzmiał w kabinie, przynosząc chwilę ulgi w tej trudnej rzeczywistości. John, Emma i Leo spędzili kilka godzin na przygotowaniach do wyjazdu. Emma pakowała wszystko, co miało jakąkolwiek wartość, a Leo nie odstępował Johna na krok, zadając mu miliony pytań o Dominatora, pustkowia i życie kierowcy. - Czemu to robisz? – zapytała Emma, gdy zostali sami. - Co takiego? – odpowiedział John, nie odwracając wzroku od mapy. - Pomagasz nam. John westchnął. – Może dlatego, że to jedyne, co potrafię. Emma spojrzała na niego z wdzięcznością, ale nie chciała naciskać. W tej chwili ważniejsze było, że mieli szansę przetrwać.`,

// Rozdział 4
`Rozdział 4: Spotkanie z Damiano
Warsztat Damiano był sercem technologicznej innowacji i zarazem miejscem, gdzie chaos spotykał się z geniuszem. Metaliczne dźwięki rozchodziły się echem, a powietrze przesycał zapach smaru i ozonu. Mechaniczne ramiona spawarki poruszały się rytmicznie, gdy Damiano, ubrany w połatany kombinezon, pracował nad jakimś futurystycznym urządzeniem. Obok niego kręcił się El Diablo – robo-pies o wyglądzie miniaturowego pinczera, którego ślepia jarzyły się delikatnym czerwonym światłem. John zatrzymał Dominatora tuż przy wejściu. Brama warsztatu uniosła się z głośnym sykiem, a Damiano podniósł wzrok znad swojej pracy. Na jego twarzy pojawił się szeroki uśmiech. - John! – wykrzyknął, odkładając narzędzia. – Jak zwykle punktualny. - Jak zwykle zajęty – odpowiedział John, wychodząc z kabiny. – Co tym razem budujesz, Damiano? - Pewnie coś, co zmieni świat – rzucił Damiano, wzruszając ramioni. – Albo coś, co wybuchnie mi w twarz. Zależy od dnia. John uśmiechnął się lekko, podając mu rękę. – Mam robotę dla ciebie. Damiano spojrzał za Johna na Dominatora. – Wygląda na to, że mój stary znajomy wciąż ma się dobrze. Ale kto to? – Wskazał na Emmę i Leo, którzy stali nieco z tyłu, niepewnie obserwując warsztat. - Pasażerowie – wyjaśnił John. – Przy okazji, potrzebuję, żebyś rzucił okiem na system komunikacyjny Dominatora. Ostatnio coś przerywa. Damiano kiwnął głową. – El Diablo, do roboty! Robo-pies zaskomlał mechanicznie i natychmiast podbiegł do Dominatora, zaczynając analizę podwozia. Leo patrzył na niego z zachwytem. - Czy on naprawdę wie, co robi? – zapytał chłopiec, wskazując na El Diablo. Damiano roześmiał się. - Lepiej, niż ja sam! Chodź, pokażę ci, jak działa. Leo podbiegł do Damiano, a Emma spojrzała na Johna z wyraźną ulgą.
Wieczór w warsztacie. Gdy dzień przeszedł w noc, a praca w warsztacie dobiegała końca, John i Damiano usiedli przy prowizorycznym stole, popijając wodę z odzysku. Emma i Leo odpoczywali w kącie warsztatu, a El Diablo pilnował terenu. - Masz ciężki ładunek? – zapytał Damiano, przechylając butelkę. - I to nie tylko w sensie dosłownym – odpowiedział John. – Prócz towaru, mam dwójkę ludzi, którzy liczą na mnie bardziej, niż chciałbym to przyznać. Damiano spojrzał na Johna z zamyśleniem. - Ty zawsze przyciągasz kłopoty, John. Ale nie oszukujmy się, właśnie to trzyma cię przy życiu. - Może masz rację – przyznał John. – Ale teraz mam ważniejszą misję. Muszę ich bezpiecznie dostarczyć do Nowego Edenu. Damiano zmarszczył brwi. - Eden to długa droga, pełna niebezpieczeństw. Ale wiesz co? Mam coś, co może ci pomóc. Damiano wstał i podszedł do jednego z regałów, wyciągając niewielkie urządzenie. - Zakłócacz sygnałów. Chroni przed wykryciem przez drony i inne technologiczne paskudztwa. John przyjął urządzenie i kiwnął głową. – Dzięki. Jak zwykle ratujesz mi skórę. Damiano uśmiechnął się szeroko. – Po to są przyjaciele, prawda?`,

// Rozdział 5
`Rozdział 5: Nocne rozmowy
Blask warsztatowych lamp oświetlał wnętrze ogromnej hali, w której Dominator zdawał się zajmować centralne miejsce. Prace przy ciężarówce dobiegły końca, a cisza wypełniła przestrzeń, przerywana jedynie cichym buczeniem generatorów. Przy jednym z prowizorycznych stołów zasiadł John i Damiano, obok nich El Diablo czuwał w pozycji przypominającej psa gotowego do działania. Emma i Leo odpoczywali w kącie, przyglądając się otoczeniu. - Ciężka trasa przed tobą, John – powiedział Damiano, nalewając wodę do kubka. – Nowy Eden to nie miejsce na wakacje. John wzruszył ramionami, patrząc na Dominatora, który lśnił po serwisie. - Nigdy nie było lekko, ale coś mi mówi, że ten kurs będzie inny. Mam wrażenie, że coraz więcej ludzi zaczyna mnie rozpoznawać. Nie wiem, czy to dobrze, czy źle. Damiano podrapał się po głowie. - Rozpoznają cię, bo masz reputację. Jesteś symbolem przetrwania. Ale pamiętaj, że symbole przyciągają uwagę, zarówno dobrą, jak i złą. - Wiem. Dlatego staram się trzymać swojego – odpowiedział John, pociągając łyk wody. – Ale teraz mam nie tylko ładunek, mam ludzi na pokładzie. Damiano spojrzał w stronę Emmy i Leo, którzy rozmawiali cicho. - Wygląda na to, że powoli zaczynasz przyzwyczajać się do towarzystwa. A może nawet potrzebujesz tego bardziej niż chcesz przyznać. John odwrócił wzrok. - Po wojnie przestałem liczyć na cokolwiek. Nie potrzebuję nikogo. Damiano uśmiechnął się lekko. - Mówisz to, a jednak nie zostawiłeś ich na pastwę losu. Może jednak jest w tobie coś więcej, John. El Diablo nagle podniósł głowę, jakby wyczuł coś w oddali. Jego mechaniczne ślepia zaświeciły się na czerwono. Damiano spojrzał na niego z niepokojem. - Co jest, mały? – zapytał, wstając od stołu. - Analiza zbliżającego się zagrożenia – odpowiedział El Diablo swoim syntetycznym głosem. – Brak potwierdzenia, ale zalecam ostrożność. John wstał i odruchowo sięgnął po broń. Spojrzał na Damiano. – Czy ktoś wie, że tu jestem? - Tylko ci, którym ufasz – odpowiedział Damiano, po czym spojrzał na system monitorujący warsztat. – Ale wiesz, jak jest. Ostrożności nigdy za wiele. Emma podeszła do nich z Leo za rękę. - Coś się dzieje? - Jeszcze nie, ale lepiej być gotowym – odpowiedział John, skinąwszy głową w stronę Dominatora. – Damiano, zabezpiecz bramę. Damiano przytaknął i podszedł do panelu kontrolnego, uruchamiając mechaniczne bariery przy wejściu do warsztatu.
Planowanie trasy. Gdy sytuacja wydawała się opanowana, grupa wróciła do stołu. Damiano rozłożył mapę, na której zaznaczył punkty potencjalnych zagrożeń. - Droga do Nowego Edenu przebiega przez kilka gorących stref – powiedział, wskazując na południowy zachód. – Bandytów przybywa, a mutanci zaczynają podchodzić coraz bliżej szlaków. - Poradzimy sobie – odparł John, ale jego głos zdradzał cień niepokoju. - Wiem, że poradzisz sobie z mutantami i bandytami – odpowiedział Damiano. – Ale pamiętaj, że czasem największe zagrożenie to ci, którzy twierdzą, że są twoimi przyjaciółmi. John spojrzał na niego pytająco, ale Damiano nie dodał nic więcej. Wstał i podszedł do Dominatora, kładąc rękę na jego opancerzeniu. - Ta maszyna to więcej niż ciężarówka, John. To twój dom, twoje schronienie. Dbaj o nią, a ona zadba o ciebie. John uśmiechnął się lekko. - Zawsze to robi.`,

// ... and so on for all chapters.
];